# This file provides instructions for packaging.

`SoundSwarm`
	perl_version_from m`SoundSwarm`;
	version_from      m`SoundSwarm`;
	readme_from       m`SoundSwarm`;
	test_requires     p`Test::More 0.61` ;
	.

